export { default as educate } from './educate.svg'
export { default as footerLogo } from './footerLogo.svg'
export { default as functional } from './functional.svg'
export { default as logo } from './logo_welbex.svg'
export { default as salles } from './salles.svg'
export { default as telegram } from './telegram.svg'
export { default as viber } from './viber.svg'
export { default as whatsapp } from './whatsapp.svg'
